### ISSUE TITLE
Conditional expiry of entries (e.g.: don't expire if CacheSource is unavailable)

### ISSUE THREAD

**Issue by gihad** [headissue/cache2k#25]
Hey,

I have a Cache object that uses a CacheSource. In my scenario entries normally expiry within 10 minutes but I would like to conditionally change the expiry time just before it's time to expire. 
One example is if the CacheSource becomes unavailable, in that case I would like to keep using the Cache in Heap and not expire the entries until the source is available again.

Some possible suggestions:

1)Provide a simple way to  disable expiring on a global Cache level,

2)On a per entry level, EntryExpiryCalculator doesn't do the calculation just before expiring but if it did the code could look similar to this:

        public long calculateExpiryTime(K _key, T _value, long _fetchTime, CacheEntry<K, T> _oldEntry) {
		   Long expiry = _oldEntry.getLastModification() + TTL;
		   /* If cachesource is down, postpone next expiration check by 30 seconds */
		   if (!heartBeat.isAlive())
		   	   expiry = _fetchTime + 30000;
		   return expiry;
	    }

3) Another alternative would be to build this as an option to the Cache configuration that when selected automatically checks the CacheSource (According to a method that the user has to implement, which returns a boolean) and disables expiry when needed.

Is there a way I can currently achieve this behaviour with the current state of the library? If not I might not be able to use Cache2K.

Thanks,
Gihad

**Comment by gihad** [comment]
Hey,

I found a stackoverflow question that you answered before and it describes a similar behaviour to what I requested: http://stackoverflow.com/questions/33751399/is-it-possible-to-configure-guava-cache-or-other-library-behaviour-to-be-if-t/33863701#33863701

Can you explain again which settings would allow the cache to be setup so that it will continue to return an entry from the heap cache indefinitely (even after expiry time has come) if the cache source is not working and when the cache source resumes working it will overwrite the entry in the heap with a newer one.

Thanks,
Gihad

**Comment by cruftex** [comment]
Gihad,

great that you found the valuable information. I am behind with documenting all these cool features :)

> Can you explain again which settings would allow the cache to be setup so that it will continue to return an entry from the heap cache indefinitely

That is the `suppressExceptions` flag. This is enabled by default, because it seems to be useful most of the time. To make your setup more explicit, I recommend specifying it never the less.

There are two additional settings, which influence the behavior. You can specify an alternative expiry, if an exception happened, with the parameter `exceptionExpiryDuration`. The basic idea is to lower the retry interval when temporary exceptions happens.

In case you have different types of exceptions, e.g. temporary or permanent, you might need a more sensible time control. This you can do by specifying a `ExceptionExpiryCaclulator`.

To close with, back to you initial request:

> In my scenario entries normally expiry within 10 minutes but I would like to conditionally change the expiry time just before it's time to expire. 

You can do some neat tricks by switching from a `CacheSource` to a `CacheSourceWithMetaInfo`, which has this signature:

     T get(K key, long _currentTime, T _previousValue, long _timeLastFetched) throws Throwable;

Since you get in the previous value, you can pass it on by yourself, if an exception happens. However, to be able to adapt the expiry time in this case you need to put some additional information in your cache entry.

Some additional remarks:

We have some kind of heart beat / service monitoring for external services as well. I always think of, whether it makes sense to signal the cache when the service comes available again. However, you need to have a priority queue and a rate limit for refreshing the entries which had an exception. I do not think the added complexity is really needed. The separate expiry time for the exception serves as priority as well as a request time distribution, to avoid a  thundering herd effect.

From our production experience, I already know, that we need more monitoring capabilities, e.g. the number of the included entries with suppressed exceptions. If you have any more ideas or needs, let me know.

**Comment by cruftex** [comment]
Closing this, since the question is answered. I have put together some plans for enhancements in this area, see #26, comments much appreciated.
